wine <- read.csv('../../dataset/whitewines.csv')
str(wine)
hist(wine$quality)
table(wine$quality)
summary(wine$quality)
length(wine$quality)
wine_train <- wine[1:3750,]
wine_test <- wine[3751:4898,]
#install.packages('rpart')
library(rpart)
m.rpart <- rpart(quality ~ ., data=wine_train)
m.rpart
#install.packages('rpart.plot')
library(rpart.plot)
rpart.plot(m.rpart, digits = 4, fallen.leaves = TRUE, type=3, extra=101)
View(wine_train$alcohol)
mean(wine_train$alcohol)
var(wine_train$alcohol)
sd(wine_train$alcohol)
sd(wine_train$alcohol)
p.rpart <- predict(m.rpart, wine_test)
summary(p.rpart)
table(p.rpart)
cor(p.rpart, wine_test$quality)
#install.packages('RWeka')
#library(RWeka)