# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alexnet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ralexnet.proto\"\x18\n\x05Shape\x12\x0f\n\x03\x64im\x18\x01 \x03(\x03\x42\x02\x10\x01\"\xbd\x01\n\x04\x42lob\x12\x15\n\x05shape\x18\x07 \x01(\x0b\x32\x06.Shape\x12\x10\n\x04\x64\x61ta\x18\x05 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x04\x64iff\x18\x06 \x03(\x02\x42\x02\x10\x01\x12\x17\n\x0b\x64ouble_data\x18\x08 \x03(\x01\x42\x02\x10\x01\x12\x17\n\x0b\x64ouble_diff\x18\t \x03(\x01\x42\x02\x10\x01\x12\x0e\n\x03num\x18\x01 \x01(\x05:\x01\x30\x12\x13\n\x08\x63hannels\x18\x02 \x01(\x05:\x01\x30\x12\x11\n\x06height\x18\x03 \x01(\x05:\x01\x30\x12\x10\n\x05width\x18\x04 \x01(\x05:\x01\x30\"\x81\x01\n\x05\x44\x61tum\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\r\n\x05label\x18\x05 \x01(\x05\x12\x12\n\nfloat_data\x18\x06 \x03(\x02\x12\x16\n\x07\x65ncoded\x18\x07 \x01(\x08:\x05\x66\x61lse\"1\n\x06\x42ranch\x12\x10\n\x04size\x18\x01 \x01(\x05:\x02\x36\x34\x12\x15\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\x06.Datum\"L\n\x05Input\x12\x0f\n\x04size\x18\x01 \x01(\x05:\x01\x30\x12\x17\n\x0b\x62ranch_size\x18\x02 \x01(\x05:\x02\x36\x34\x12\x19\n\x08\x62ranches\x18\x03 \x03(\x0b\x32\x07.Branch')



_SHAPE = DESCRIPTOR.message_types_by_name['Shape']
_BLOB = DESCRIPTOR.message_types_by_name['Blob']
_DATUM = DESCRIPTOR.message_types_by_name['Datum']
_BRANCH = DESCRIPTOR.message_types_by_name['Branch']
_INPUT = DESCRIPTOR.message_types_by_name['Input']
Shape = _reflection.GeneratedProtocolMessageType('Shape', (_message.Message,), {
  'DESCRIPTOR' : _SHAPE,
  '__module__' : 'alexnet_pb2'
  # @@protoc_insertion_point(class_scope:Shape)
  })
_sym_db.RegisterMessage(Shape)

Blob = _reflection.GeneratedProtocolMessageType('Blob', (_message.Message,), {
  'DESCRIPTOR' : _BLOB,
  '__module__' : 'alexnet_pb2'
  # @@protoc_insertion_point(class_scope:Blob)
  })
_sym_db.RegisterMessage(Blob)

Datum = _reflection.GeneratedProtocolMessageType('Datum', (_message.Message,), {
  'DESCRIPTOR' : _DATUM,
  '__module__' : 'alexnet_pb2'
  # @@protoc_insertion_point(class_scope:Datum)
  })
_sym_db.RegisterMessage(Datum)

Branch = _reflection.GeneratedProtocolMessageType('Branch', (_message.Message,), {
  'DESCRIPTOR' : _BRANCH,
  '__module__' : 'alexnet_pb2'
  # @@protoc_insertion_point(class_scope:Branch)
  })
_sym_db.RegisterMessage(Branch)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'alexnet_pb2'
  # @@protoc_insertion_point(class_scope:Input)
  })
_sym_db.RegisterMessage(Input)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHAPE.fields_by_name['dim']._options = None
  _SHAPE.fields_by_name['dim']._serialized_options = b'\020\001'
  _BLOB.fields_by_name['data']._options = None
  _BLOB.fields_by_name['data']._serialized_options = b'\020\001'
  _BLOB.fields_by_name['diff']._options = None
  _BLOB.fields_by_name['diff']._serialized_options = b'\020\001'
  _BLOB.fields_by_name['double_data']._options = None
  _BLOB.fields_by_name['double_data']._serialized_options = b'\020\001'
  _BLOB.fields_by_name['double_diff']._options = None
  _BLOB.fields_by_name['double_diff']._serialized_options = b'\020\001'
  _SHAPE._serialized_start=17
  _SHAPE._serialized_end=41
  _BLOB._serialized_start=44
  _BLOB._serialized_end=233
  _DATUM._serialized_start=236
  _DATUM._serialized_end=365
  _BRANCH._serialized_start=367
  _BRANCH._serialized_end=416
  _INPUT._serialized_start=418
  _INPUT._serialized_end=494
# @@protoc_insertion_point(module_scope)
