steel_train <- read.csv('../../dataset/kaggle/severstal-steel-defect-detection/train.csv')
summary(steel_train)
length(steel_train)
summary(steel_train$ImageId_ClassId)
summary(steel_train$EncodedPixels)
length(steel_train$ImageId_ClassId)
